version: "3.8"
name: "datawarehouse"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=simple_datawarehouse
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=simple_datawarehouse
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
